{{- $db := ( tpl .Values.config.database.dbname . ) }}
{{- $host := .Values.config.database.host | default (include "nebraska.postgresql.fullname" .) }}
{{- $port := .Values.config.database.port | toString }}
{{- $sslMode := .Values.config.database.sslMode | default "disable" }}
{{- $user := ( tpl .Values.config.database.username . ) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nebraska.fullname" . }}
  labels:
    {{- include "nebraska.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nebraska.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nebraska.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nebraska.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "nebraska.image" ( dict "imageRoot" .Values.image "global" .Values.global "context" $) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/nebraska/nebraska"
          args:
            {{- /* --- General settings --- */}}
            {{- if .Values.config.app.title }}
            - "-client-title={{ .Values.config.app.title }}"
            {{- end }}
            {{- if .Values.config.app.logoPath }}
            - "-client-logo={{ .Values.config.app.logoPath }}"
            {{- end }}
            {{- if .Values.config.app.headerStyle }}
            - "-client-header-style={{ .Values.config.app.headerStyle }}"
            {{- end }}
            {{- if .Values.config.app.httpStaticDir }}
            - "-http-static-dir={{ .Values.config.app.httpStaticDir }}"
            {{- end }}

            {{- /* --- Syncer settings --- */}}
            {{- if .Values.config.syncer.enabled }}
            - "-enable-syncer"
              {{- if .Values.config.syncer.interval }}
            - "-sync-interval={{ .Values.config.syncer.interval }}"
              {{- end }}
              {{- if .Values.config.syncer.updateURL }}
            - "-sync-update-url={{ .Values.config.syncer.updateURL }}"
              {{- end }}
            {{- end }}

            {{- /* --- Host packages settings --- */}}
            {{- if .Values.config.hostFlatcarPackages.enabled }}
            - "-host-flatcar-packages"
            - "-flatcar-packages-path={{ required "A valid 'packagesPath' is required when hosting Flatcar packages." .Values.config.hostFlatcarPackages.packagesPath }}"
            {{- end }}

            {{- /* --- Nebraska URL settings ---*/}}
            {{- if .Values.config.hostFlatcarPackages.nebraskaURL }}
            - "-nebraska-url={{ .Values.config.hostFlatcarPackages.nebraskaURL }}"
            {{- else if .Values.ingress.enabled }}
            - "-nebraska-url={{ printf "%s://%s"  (include "nebraska.ingressScheme" .) (index .Values.ingress.hosts 0) }}"
            {{- end }}

            {{- /* --- Auth settings --- */}}
            {{- if .Values.config.auth.mode }}
            - "-auth-mode={{ .Values.config.auth.mode }}"
            {{- end }}
            {{- if eq .Values.config.auth.mode "github" }}
              {{- if .Values.config.auth.github.readWriteTeams }}
            - "-gh-rw-teams={{ .Values.config.auth.github.readWriteTeams }}"
              {{- end }}
              {{- if .Values.config.auth.github.readOnlyTeams }}
            - "-gh-ro-teams={{ .Values.config.auth.github.readOnlyTeams }}"
              {{- end }}
            {{- end }}
            {{- if eq .Values.config.auth.mode "oidc" }}
              {{- with .Values.config.auth.oidc.issuerURL }}
            - "-oidc-issuer-url={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.validRedirectURLs }}
            - "-oidc-valid-redirect-urls={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.managementURL }}
            - "-oidc-management-url={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.logoutURL }}
            - "-oidc-logout-url={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.adminRoles }}
            - "-oidc-admin-roles={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.viewerRoles }}
            - "-oidc-viewer-roles={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.rolesPath }}
            - "-oidc-roles-path={{ . }}"
              {{- end }}
              {{- with .Values.config.auth.oidc.scopes }}
            - "-oidc-scopes={{ . }}"
              {{- end }}
            {{- end }}

            {{- /* --- Extra Args --- */ -}}
            {{- if .Values.extraArgs }}
            {{- range .Values.extraArgs }}
            - "{{ . }}"
            {{- end }}
            {{- end }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.config.database.passwordExistingSecret.enabled }}
                  name: {{ tpl .Values.config.database.passwordExistingSecret.name . }}
                  key: {{ .Values.config.database.passwordExistingSecret.key }}
                  {{- else }}
                  name: {{ include "nebraska.fullname" . }}
                  key: dbPassword
                  {{- end }}
            - name: NEBRASKA_DB_URL
              value: {{ printf "postgres://%s:$(DB_PASSWORD)@%s:%s/%s?sslmode=%s&connect_timeout=10" $user $host $port $db $sslMode | quote }}
            {{- if eq .Values.config.auth.mode "github" }}
            - name: "NEBRASKA_GITHUB_OAUTH_CLIENT_ID"
              value: "{{ .Values.config.auth.github.clientID }}"
            - name: "NEBRASKA_GITHUB_OAUTH_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.config.auth.github.existingSecret }}
                  name: {{ include "nebraska.fullname" . }}
                  {{- else }}
                  name: {{ .Values.config.auth.github.existingSecret }}
                  {{- end }}
                  key: ghClientSecret
            - name: "NEBRASKA_GITHUB_SESSION_SECRET"
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.config.auth.github.existingSecret }}
                  name: {{ include "nebraska.fullname" . }}
                  {{- else }}
                  name: {{ .Values.config.auth.github.existingSecret }}
                  {{- end }}
                  key: ghSessionAuthKey
            - name: "NEBRASKA_GITHUB_SESSION_CRYPT_KEY"
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.config.auth.github.existingSecret }}
                  name: {{ include "nebraska.fullname" . }}
                  {{- else }}
                  name: {{ .Values.config.auth.github.existingSecret }}
                  {{- end }}
                  key: ghSessionCryptKey
            - name: "NEBRASKA_GITHUB_WEBHOOK_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebraska.fullname" . }}
                  key: ghWebhookSecret
              {{- if .Values.config.auth.github.enterpriseURL }}
            - name: "NEBRASKA_GITHUB_ENTERPRISE_URL"
              value: "{{ .Values.config.auth.github.enterpriseURL }}"
              {{- end }}
            {{- end }}
            {{- if eq .Values.config.auth.mode "oidc" }}
            - name: "NEBRASKA_OIDC_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.config.auth.oidc.existingSecret }}
                  name: {{ include "nebraska.fullname" . }}
                  {{- else }}
                  name: {{ .Values.config.auth.oidc.existingSecret }}
                  {{- end }}
                  key: oidcClientID
            - name: "NEBRASKA_OIDC_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.config.auth.oidc.existingSecret }}
                  name: {{ include "nebraska.fullname" . }}
                  {{- else }}
                  name: {{ .Values.config.auth.oidc.existingSecret }}
                  {{- end }}
                  key: oidcClientSecret
            {{- if .Values.config.auth.oidc.sessionAuthKey }}
            - name: "NEBRASKA_OIDC_SESSION_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebraska.fullname" . }}
                  key: oidcSessionAuthKey
            {{- end }}
            {{- if .Values.config.auth.oidc.sessionCryptKey }}
            - name: "NEBRASKA_OIDC_SESSION_CRYPT_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebraska.fullname" . }}
                  key: oidcSessionCryptKey
            {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnv }}
            # Extra environment variables
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          {{- if .Values.config.hostFlatcarPackages.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.config.hostFlatcarPackages.packagesPath }}
              name: packages
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.extraEnvVars.PORT | default 8000 }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.config.hostFlatcarPackages.enabled }}
      volumes:
        - name: packages
          {{- if .Values.config.hostFlatcarPackages.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nebraska.fullname" . }}-packages
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
