name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/cmd/**'
    - 'backend/pkg/**'
    - 'backend/tools/**'
    - 'backend/test/**'
    - 'backend/go.mod'
    - 'backend/go.sum'
    - 'updaters/**'
    - '.github/**'
    - Makefile

jobs:

  build:
    name: Backend Build Steps
    runs-on: ubuntu-24.04

    steps:

    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: ./backend/go.mod
      id: go

    - name: Build, Lint & Check
      run: |
        make all ci
      working-directory: backend
