name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/cmd/**'
    - 'backend/pkg/**'
    - 'backend/tools/**'
    - 'backend/test/**'
    - 'backend/go.mod'
    - 'backend/go.sum'
    - 'updaters/**'
    - '.github/**'
    - Makefile

jobs:

  build:
    name: Lint & Build
    runs-on: ubuntu-22.04

    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: 1.22.x
      id: go

    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build, Lint & Check
      run: |
        make all ci
      working-directory: backend
