name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/cmd/**'
    - 'backend/pkg/**'
    - 'backend/tools/**'
    - 'backend/test/**'
    - 'backend/go.mod'
    - 'backend/go.sum'
    - 'updaters/**'
    - '.github/**'
    - Makefile

jobs:

  build:
    name: Backend Build Steps
    runs-on: ubuntu-24.04

    steps:

    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: ./backend/go.mod
      id: go

    - name: Build, Lint & Check
      run: |
        make all ci
      working-directory: backend
