name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/cmd/**'
    - 'backend/pkg/**'
    - 'backend/tools/**'
    - 'backend/go.mod'
    - 'backend/go.sum'
    - 'updaters/**'
    - '.github/**'
    - Makefile

jobs:

  build:
    name: Lint & Build
    runs-on: ubuntu-20.04

    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build, Lint & Check
      run: |
        cd $GITHUB_WORKSPACE
        make backend-ci
