name: Build Backend
on:
  pull_request:
    paths:
    - 'backend/cmd/**'
    - 'backend/pkg/**'
    - 'backend/tools/**'
    - 'backend/test/**'
    - 'backend/go.mod'
    - 'backend/go.sum'
    - 'updaters/**'
    - '.github/**'
    - Makefile

jobs:

  build:
    name: Backend Build Steps
    runs-on: ubuntu-24.04

    steps:

    - name: Check out code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: ./backend/go.mod
      id: go

    - name: Build, Lint & Check
      run: |
        make all ci
      working-directory: backend
